export default function Head() {
  return (
    <>
      <title>Next 13 Movies</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta
        content="Next 13 Movies - real app example using Next 13 Movies"
        name="description"
      />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
